#ifndef FILECACHERLIB_GLOBAL_H
#define FILECACHERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILECACHERLIB_LIBRARY)
#  define FILECACHERLIB_EXPORT Q_DECL_EXPORT
#else
#  define FILECACHERLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // FILECACHERLIB_GLOBAL_H
