#ifndef IMGVIEWERLABELWIDGET_GLOBAL_H
#define IMGVIEWERLABELWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMGVIEWERLABELWIDGET_LIBRARY)
#  define IMGVIEWERLABELWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define IMGVIEWERLABELWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // IMGVIEWERLABELWIDGET_GLOBAL_H
